trigger:
  branches:
    include:
      - main  # Adjust if your Azure branch is named differently

pool:
  vmImage: ubuntu-latest

variables:
  GITHUB_USERNAME: 'DevLok2017'                # Your GitHub username
  GITHUB_REPO: 'Test-Repo-Clone'               # The repo name on GitHub
  GITHUB_TOKEN: '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'

steps:
  - checkout: self

  - script: |
      echo "Adding GitHub remote..."
      git remote add github https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@github.com/$(GITHUB_USERNAME)/$(GITHUB_REPO).git
      
      echo "Force-pushing main branch to GitHub..."
      git push -f github HEAD:main
    displayName: 'Force-push main branch to GitHub'